// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.assignSkillToAgentStmt, err = db.PrepareContext(ctx, assignSkillToAgent); err != nil {
		return nil, fmt.Errorf("error preparing query AssignSkillToAgent: %w", err)
	}
	if q.createAgentStmt, err = db.PrepareContext(ctx, createAgent); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAgent: %w", err)
	}
	if q.createAttachmentStmt, err = db.PrepareContext(ctx, createAttachment); err != nil {
		return nil, fmt.Errorf("error preparing query CreateAttachment: %w", err)
	}
	if q.createCommentStmt, err = db.PrepareContext(ctx, createComment); err != nil {
		return nil, fmt.Errorf("error preparing query CreateComment: %w", err)
	}
	if q.createCompanyStmt, err = db.PrepareContext(ctx, createCompany); err != nil {
		return nil, fmt.Errorf("error preparing query CreateCompany: %w", err)
	}
	if q.createLLMProviderStmt, err = db.PrepareContext(ctx, createLLMProvider); err != nil {
		return nil, fmt.Errorf("error preparing query CreateLLMProvider: %w", err)
	}
	if q.createProjectStmt, err = db.PrepareContext(ctx, createProject); err != nil {
		return nil, fmt.Errorf("error preparing query CreateProject: %w", err)
	}
	if q.createRunStmt, err = db.PrepareContext(ctx, createRun); err != nil {
		return nil, fmt.Errorf("error preparing query CreateRun: %w", err)
	}
	if q.createSkillStmt, err = db.PrepareContext(ctx, createSkill); err != nil {
		return nil, fmt.Errorf("error preparing query CreateSkill: %w", err)
	}
	if q.createTaskStmt, err = db.PrepareContext(ctx, createTask); err != nil {
		return nil, fmt.Errorf("error preparing query CreateTask: %w", err)
	}
	if q.getAgentStmt, err = db.PrepareContext(ctx, getAgent); err != nil {
		return nil, fmt.Errorf("error preparing query GetAgent: %w", err)
	}
	if q.getLLMProviderStmt, err = db.PrepareContext(ctx, getLLMProvider); err != nil {
		return nil, fmt.Errorf("error preparing query GetLLMProvider: %w", err)
	}
	if q.getTaskStmt, err = db.PrepareContext(ctx, getTask); err != nil {
		return nil, fmt.Errorf("error preparing query GetTask: %w", err)
	}
	if q.listAgentsByCompanyStmt, err = db.PrepareContext(ctx, listAgentsByCompany); err != nil {
		return nil, fmt.Errorf("error preparing query ListAgentsByCompany: %w", err)
	}
	if q.listAttachmentsByTaskStmt, err = db.PrepareContext(ctx, listAttachmentsByTask); err != nil {
		return nil, fmt.Errorf("error preparing query ListAttachmentsByTask: %w", err)
	}
	if q.listCommentsByTaskStmt, err = db.PrepareContext(ctx, listCommentsByTask); err != nil {
		return nil, fmt.Errorf("error preparing query ListCommentsByTask: %w", err)
	}
	if q.listCompaniesStmt, err = db.PrepareContext(ctx, listCompanies); err != nil {
		return nil, fmt.Errorf("error preparing query ListCompanies: %w", err)
	}
	if q.listLLMProvidersStmt, err = db.PrepareContext(ctx, listLLMProviders); err != nil {
		return nil, fmt.Errorf("error preparing query ListLLMProviders: %w", err)
	}
	if q.listProjectsByCompanyStmt, err = db.PrepareContext(ctx, listProjectsByCompany); err != nil {
		return nil, fmt.Errorf("error preparing query ListProjectsByCompany: %w", err)
	}
	if q.listTasksByProjectStmt, err = db.PrepareContext(ctx, listTasksByProject); err != nil {
		return nil, fmt.Errorf("error preparing query ListTasksByProject: %w", err)
	}
	if q.updateRunLogStmt, err = db.PrepareContext(ctx, updateRunLog); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateRunLog: %w", err)
	}
	if q.updateTaskStatusStmt, err = db.PrepareContext(ctx, updateTaskStatus); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateTaskStatus: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.assignSkillToAgentStmt != nil {
		if cerr := q.assignSkillToAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing assignSkillToAgentStmt: %w", cerr)
		}
	}
	if q.createAgentStmt != nil {
		if cerr := q.createAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAgentStmt: %w", cerr)
		}
	}
	if q.createAttachmentStmt != nil {
		if cerr := q.createAttachmentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createAttachmentStmt: %w", cerr)
		}
	}
	if q.createCommentStmt != nil {
		if cerr := q.createCommentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCommentStmt: %w", cerr)
		}
	}
	if q.createCompanyStmt != nil {
		if cerr := q.createCompanyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createCompanyStmt: %w", cerr)
		}
	}
	if q.createLLMProviderStmt != nil {
		if cerr := q.createLLMProviderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createLLMProviderStmt: %w", cerr)
		}
	}
	if q.createProjectStmt != nil {
		if cerr := q.createProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createProjectStmt: %w", cerr)
		}
	}
	if q.createRunStmt != nil {
		if cerr := q.createRunStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createRunStmt: %w", cerr)
		}
	}
	if q.createSkillStmt != nil {
		if cerr := q.createSkillStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createSkillStmt: %w", cerr)
		}
	}
	if q.createTaskStmt != nil {
		if cerr := q.createTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing createTaskStmt: %w", cerr)
		}
	}
	if q.getAgentStmt != nil {
		if cerr := q.getAgentStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getAgentStmt: %w", cerr)
		}
	}
	if q.getLLMProviderStmt != nil {
		if cerr := q.getLLMProviderStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getLLMProviderStmt: %w", cerr)
		}
	}
	if q.getTaskStmt != nil {
		if cerr := q.getTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing getTaskStmt: %w", cerr)
		}
	}
	if q.listAgentsByCompanyStmt != nil {
		if cerr := q.listAgentsByCompanyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAgentsByCompanyStmt: %w", cerr)
		}
	}
	if q.listAttachmentsByTaskStmt != nil {
		if cerr := q.listAttachmentsByTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listAttachmentsByTaskStmt: %w", cerr)
		}
	}
	if q.listCommentsByTaskStmt != nil {
		if cerr := q.listCommentsByTaskStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCommentsByTaskStmt: %w", cerr)
		}
	}
	if q.listCompaniesStmt != nil {
		if cerr := q.listCompaniesStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listCompaniesStmt: %w", cerr)
		}
	}
	if q.listLLMProvidersStmt != nil {
		if cerr := q.listLLMProvidersStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listLLMProvidersStmt: %w", cerr)
		}
	}
	if q.listProjectsByCompanyStmt != nil {
		if cerr := q.listProjectsByCompanyStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listProjectsByCompanyStmt: %w", cerr)
		}
	}
	if q.listTasksByProjectStmt != nil {
		if cerr := q.listTasksByProjectStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing listTasksByProjectStmt: %w", cerr)
		}
	}
	if q.updateRunLogStmt != nil {
		if cerr := q.updateRunLogStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateRunLogStmt: %w", cerr)
		}
	}
	if q.updateTaskStatusStmt != nil {
		if cerr := q.updateTaskStatusStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateTaskStatusStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                        DBTX
	tx                        *sql.Tx
	assignSkillToAgentStmt    *sql.Stmt
	createAgentStmt           *sql.Stmt
	createAttachmentStmt      *sql.Stmt
	createCommentStmt         *sql.Stmt
	createCompanyStmt         *sql.Stmt
	createLLMProviderStmt     *sql.Stmt
	createProjectStmt         *sql.Stmt
	createRunStmt             *sql.Stmt
	createSkillStmt           *sql.Stmt
	createTaskStmt            *sql.Stmt
	getAgentStmt              *sql.Stmt
	getLLMProviderStmt        *sql.Stmt
	getTaskStmt               *sql.Stmt
	listAgentsByCompanyStmt   *sql.Stmt
	listAttachmentsByTaskStmt *sql.Stmt
	listCommentsByTaskStmt    *sql.Stmt
	listCompaniesStmt         *sql.Stmt
	listLLMProvidersStmt      *sql.Stmt
	listProjectsByCompanyStmt *sql.Stmt
	listTasksByProjectStmt    *sql.Stmt
	updateRunLogStmt          *sql.Stmt
	updateTaskStatusStmt      *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                        tx,
		tx:                        tx,
		assignSkillToAgentStmt:    q.assignSkillToAgentStmt,
		createAgentStmt:           q.createAgentStmt,
		createAttachmentStmt:      q.createAttachmentStmt,
		createCommentStmt:         q.createCommentStmt,
		createCompanyStmt:         q.createCompanyStmt,
		createLLMProviderStmt:     q.createLLMProviderStmt,
		createProjectStmt:         q.createProjectStmt,
		createRunStmt:             q.createRunStmt,
		createSkillStmt:           q.createSkillStmt,
		createTaskStmt:            q.createTaskStmt,
		getAgentStmt:              q.getAgentStmt,
		getLLMProviderStmt:        q.getLLMProviderStmt,
		getTaskStmt:               q.getTaskStmt,
		listAgentsByCompanyStmt:   q.listAgentsByCompanyStmt,
		listAttachmentsByTaskStmt: q.listAttachmentsByTaskStmt,
		listCommentsByTaskStmt:    q.listCommentsByTaskStmt,
		listCompaniesStmt:         q.listCompaniesStmt,
		listLLMProvidersStmt:      q.listLLMProvidersStmt,
		listProjectsByCompanyStmt: q.listProjectsByCompanyStmt,
		listTasksByProjectStmt:    q.listTasksByProjectStmt,
		updateRunLogStmt:          q.updateRunLogStmt,
		updateTaskStatusStmt:      q.updateTaskStatusStmt,
	}
}
