// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Agent struct {
	ID           int32          `json:"id"`
	CompanyID    int32          `json:"company_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	SystemPrompt string         `json:"system_prompt"`
	ProviderID   sql.NullInt32  `json:"provider_id"`
	Model        sql.NullString `json:"model"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type AgentSkill struct {
	AgentID int32 `json:"agent_id"`
	SkillID int32 `json:"skill_id"`
}

type Attachment struct {
	ID        int32          `json:"id"`
	TaskID    int32          `json:"task_id"`
	CommentID sql.NullInt32  `json:"comment_id"`
	Filename  string         `json:"filename"`
	FilePath  string         `json:"file_path"`
	MimeType  sql.NullString `json:"mime_type"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type Comment struct {
	ID         int32         `json:"id"`
	TaskID     int32         `json:"task_id"`
	AuthorType string        `json:"author_type"`
	AuthorID   sql.NullInt32 `json:"author_id"`
	Content    string        `json:"content"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	UpdatedAt  sql.NullTime  `json:"updated_at"`
}

type Company struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type LlmProvider struct {
	ID        int32        `json:"id"`
	Name      string       `json:"name"`
	BaseUrl   string       `json:"base_url"`
	ApiKey    string       `json:"api_key"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type Project struct {
	ID          int32          `json:"id"`
	CompanyID   int32          `json:"company_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Run struct {
	ID          int32          `json:"id"`
	TaskID      int32          `json:"task_id"`
	AgentID     int32          `json:"agent_id"`
	Status      string         `json:"status"`
	LogFilePath sql.NullString `json:"log_file_path"`
	LogContent  sql.NullString `json:"log_content"`
	StartedAt   sql.NullTime   `json:"started_at"`
	EndedAt     sql.NullTime   `json:"ended_at"`
}

type Skill struct {
	ID          int32          `json:"id"`
	CompanyID   int32          `json:"company_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	SourceUrl   sql.NullString `json:"source_url"`
	LocalPath   string         `json:"local_path"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Task struct {
	ID          int32          `json:"id"`
	ProjectID   int32          `json:"project_id"`
	AgentID     sql.NullInt32  `json:"agent_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}
