// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const assignSkillToAgent = `-- name: AssignSkillToAgent :exec
INSERT INTO agent_skills (agent_id, skill_id) VALUES ($1, $2)
`

type AssignSkillToAgentParams struct {
	AgentID int32 `json:"agent_id"`
	SkillID int32 `json:"skill_id"`
}

func (q *Queries) AssignSkillToAgent(ctx context.Context, arg AssignSkillToAgentParams) error {
	_, err := q.exec(ctx, q.assignSkillToAgentStmt, assignSkillToAgent, arg.AgentID, arg.SkillID)
	return err
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (company_id, name, description, system_prompt, provider_id, model)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, company_id, name, description, system_prompt, provider_id, model, created_at, updated_at
`

type CreateAgentParams struct {
	CompanyID    int32          `json:"company_id"`
	Name         string         `json:"name"`
	Description  sql.NullString `json:"description"`
	SystemPrompt string         `json:"system_prompt"`
	ProviderID   sql.NullInt32  `json:"provider_id"`
	Model        sql.NullString `json:"model"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.queryRow(ctx, q.createAgentStmt, createAgent,
		arg.CompanyID,
		arg.Name,
		arg.Description,
		arg.SystemPrompt,
		arg.ProviderID,
		arg.Model,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ProviderID,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (task_id, comment_id, filename, file_path, mime_type)
VALUES ($1, $2, $3, $4, $5) RETURNING id, task_id, comment_id, filename, file_path, mime_type, created_at
`

type CreateAttachmentParams struct {
	TaskID    int32          `json:"task_id"`
	CommentID sql.NullInt32  `json:"comment_id"`
	Filename  string         `json:"filename"`
	FilePath  string         `json:"file_path"`
	MimeType  sql.NullString `json:"mime_type"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.queryRow(ctx, q.createAttachmentStmt, createAttachment,
		arg.TaskID,
		arg.CommentID,
		arg.Filename,
		arg.FilePath,
		arg.MimeType,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.CommentID,
		&i.Filename,
		&i.FilePath,
		&i.MimeType,
		&i.CreatedAt,
	)
	return i, err
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (task_id, author_type, author_id, content)
VALUES ($1, $2, $3, $4) RETURNING id, task_id, author_type, author_id, content, created_at, updated_at
`

type CreateCommentParams struct {
	TaskID     int32         `json:"task_id"`
	AuthorType string        `json:"author_type"`
	AuthorID   sql.NullInt32 `json:"author_id"`
	Content    string        `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.queryRow(ctx, q.createCommentStmt, createComment,
		arg.TaskID,
		arg.AuthorType,
		arg.AuthorID,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AuthorType,
		&i.AuthorID,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (name) VALUES ($1) RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateCompany(ctx context.Context, name string) (Company, error) {
	row := q.queryRow(ctx, q.createCompanyStmt, createCompany, name)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createLLMProvider = `-- name: CreateLLMProvider :one
INSERT INTO llm_providers (name, base_url, api_key)
VALUES ($1, $2, $3) RETURNING id, name, base_url, api_key, created_at, updated_at
`

type CreateLLMProviderParams struct {
	Name    string `json:"name"`
	BaseUrl string `json:"base_url"`
	ApiKey  string `json:"api_key"`
}

func (q *Queries) CreateLLMProvider(ctx context.Context, arg CreateLLMProviderParams) (LlmProvider, error) {
	row := q.queryRow(ctx, q.createLLMProviderStmt, createLLMProvider, arg.Name, arg.BaseUrl, arg.ApiKey)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (company_id, name, description) VALUES ($1, $2, $3) RETURNING id, company_id, name, description, created_at, updated_at
`

type CreateProjectParams struct {
	CompanyID   int32          `json:"company_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.queryRow(ctx, q.createProjectStmt, createProject, arg.CompanyID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRun = `-- name: CreateRun :one
INSERT INTO runs (task_id, agent_id, status)
VALUES ($1, $2, $3) RETURNING id, task_id, agent_id, status, log_file_path, log_content, started_at, ended_at
`

type CreateRunParams struct {
	TaskID  int32  `json:"task_id"`
	AgentID int32  `json:"agent_id"`
	Status  string `json:"status"`
}

func (q *Queries) CreateRun(ctx context.Context, arg CreateRunParams) (Run, error) {
	row := q.queryRow(ctx, q.createRunStmt, createRun, arg.TaskID, arg.AgentID, arg.Status)
	var i Run
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.AgentID,
		&i.Status,
		&i.LogFilePath,
		&i.LogContent,
		&i.StartedAt,
		&i.EndedAt,
	)
	return i, err
}

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (company_id, name, description, source_url, local_path)
VALUES ($1, $2, $3, $4, $5) RETURNING id, company_id, name, description, source_url, local_path, created_at, updated_at
`

type CreateSkillParams struct {
	CompanyID   int32          `json:"company_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	SourceUrl   sql.NullString `json:"source_url"`
	LocalPath   string         `json:"local_path"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.queryRow(ctx, q.createSkillStmt, createSkill,
		arg.CompanyID,
		arg.Name,
		arg.Description,
		arg.SourceUrl,
		arg.LocalPath,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.SourceUrl,
		&i.LocalPath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, agent_id, title, description, status)
VALUES ($1, $2, $3, $4, $5) RETURNING id, project_id, agent_id, title, description, status, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID   int32          `json:"project_id"`
	AgentID     sql.NullInt32  `json:"agent_id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Status      string         `json:"status"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.queryRow(ctx, q.createTaskStmt, createTask,
		arg.ProjectID,
		arg.AgentID,
		arg.Title,
		arg.Description,
		arg.Status,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAgent = `-- name: GetAgent :one
SELECT id, company_id, name, description, system_prompt, provider_id, model, created_at, updated_at FROM agents WHERE id = $1
`

func (q *Queries) GetAgent(ctx context.Context, id int32) (Agent, error) {
	row := q.queryRow(ctx, q.getAgentStmt, getAgent, id)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Name,
		&i.Description,
		&i.SystemPrompt,
		&i.ProviderID,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLLMProvider = `-- name: GetLLMProvider :one
SELECT id, name, base_url, api_key, created_at, updated_at FROM llm_providers WHERE id = $1
`

func (q *Queries) GetLLMProvider(ctx context.Context, id int32) (LlmProvider, error) {
	row := q.queryRow(ctx, q.getLLMProviderStmt, getLLMProvider, id)
	var i LlmProvider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BaseUrl,
		&i.ApiKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, project_id, agent_id, title, description, status, created_at, updated_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id int32) (Task, error) {
	row := q.queryRow(ctx, q.getTaskStmt, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAgentsByCompany = `-- name: ListAgentsByCompany :many
SELECT id, company_id, name, description, system_prompt, provider_id, model, created_at, updated_at FROM agents WHERE company_id = $1 ORDER BY id
`

func (q *Queries) ListAgentsByCompany(ctx context.Context, companyID int32) ([]Agent, error) {
	rows, err := q.query(ctx, q.listAgentsByCompanyStmt, listAgentsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Agent
	for rows.Next() {
		var i Agent
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.SystemPrompt,
			&i.ProviderID,
			&i.Model,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttachmentsByTask = `-- name: ListAttachmentsByTask :many
SELECT id, task_id, comment_id, filename, file_path, mime_type, created_at FROM attachments WHERE task_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListAttachmentsByTask(ctx context.Context, taskID int32) ([]Attachment, error) {
	rows, err := q.query(ctx, q.listAttachmentsByTaskStmt, listAttachmentsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Attachment
	for rows.Next() {
		var i Attachment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.CommentID,
			&i.Filename,
			&i.FilePath,
			&i.MimeType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentsByTask = `-- name: ListCommentsByTask :many
SELECT id, task_id, author_type, author_id, content, created_at, updated_at FROM comments WHERE task_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListCommentsByTask(ctx context.Context, taskID int32) ([]Comment, error) {
	rows, err := q.query(ctx, q.listCommentsByTaskStmt, listCommentsByTask, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.AuthorType,
			&i.AuthorID,
			&i.Content,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, created_at, updated_at FROM companies ORDER BY id
`

func (q *Queries) ListCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.query(ctx, q.listCompaniesStmt, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLLMProviders = `-- name: ListLLMProviders :many
SELECT id, name, base_url, api_key, created_at, updated_at FROM llm_providers ORDER BY id
`

func (q *Queries) ListLLMProviders(ctx context.Context) ([]LlmProvider, error) {
	rows, err := q.query(ctx, q.listLLMProvidersStmt, listLLMProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LlmProvider
	for rows.Next() {
		var i LlmProvider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BaseUrl,
			&i.ApiKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByCompany = `-- name: ListProjectsByCompany :many
SELECT id, company_id, name, description, created_at, updated_at FROM projects WHERE company_id = $1 ORDER BY id
`

func (q *Queries) ListProjectsByCompany(ctx context.Context, companyID int32) ([]Project, error) {
	rows, err := q.query(ctx, q.listProjectsByCompanyStmt, listProjectsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByProject = `-- name: ListTasksByProject :many
SELECT id, project_id, agent_id, title, description, status, created_at, updated_at FROM tasks WHERE project_id = $1 ORDER BY id
`

func (q *Queries) ListTasksByProject(ctx context.Context, projectID int32) ([]Task, error) {
	rows, err := q.query(ctx, q.listTasksByProjectStmt, listTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AgentID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRunLog = `-- name: UpdateRunLog :exec
UPDATE runs SET log_content = $2, status = $3, ended_at = $4 WHERE id = $1
`

type UpdateRunLogParams struct {
	ID         int32          `json:"id"`
	LogContent sql.NullString `json:"log_content"`
	Status     string         `json:"status"`
	EndedAt    sql.NullTime   `json:"ended_at"`
}

func (q *Queries) UpdateRunLog(ctx context.Context, arg UpdateRunLogParams) error {
	_, err := q.exec(ctx, q.updateRunLogStmt, updateRunLog,
		arg.ID,
		arg.LogContent,
		arg.Status,
		arg.EndedAt,
	)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks SET status = $2, updated_at = CURRENT_TIMESTAMP WHERE id = $1 RETURNING id, project_id, agent_id, title, description, status, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	ID     int32  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.queryRow(ctx, q.updateTaskStatusStmt, updateTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AgentID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
