// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AssignSkillToAgent(ctx context.Context, arg AssignSkillToAgentParams) error
	CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateCompany(ctx context.Context, name string) (Company, error)
	CreateLLMProvider(ctx context.Context, arg CreateLLMProviderParams) (LlmProvider, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateRun(ctx context.Context, arg CreateRunParams) (Run, error)
	CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	GetAgent(ctx context.Context, id int32) (Agent, error)
	GetLLMProvider(ctx context.Context, id int32) (LlmProvider, error)
	GetTask(ctx context.Context, id int32) (Task, error)
	ListAgentsByCompany(ctx context.Context, companyID int32) ([]Agent, error)
	ListAttachmentsByTask(ctx context.Context, taskID int32) ([]Attachment, error)
	ListCommentsByTask(ctx context.Context, taskID int32) ([]Comment, error)
	ListCompanies(ctx context.Context) ([]Company, error)
	ListLLMProviders(ctx context.Context) ([]LlmProvider, error)
	ListProjectsByCompany(ctx context.Context, companyID int32) ([]Project, error)
	ListTasksByProject(ctx context.Context, projectID int32) ([]Task, error)
	UpdateRunLog(ctx context.Context, arg UpdateRunLogParams) error
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
}

var _ Querier = (*Queries)(nil)
